# Base configs
baseurl: ".github.io/photography"
# baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Tarun Sreepada"
subtitle: "See the world through my eyes!"
author: "Tarun Sreepada
header:
 title: "Photography"
 subtitle: "by Tarun Sreepada"
footer:
 name: "Hey there, my name is Tarun"
 bio: "I am a student and I like computers and cats. And photography."
 #github: ""
web_design: "AJ"

social_urls:
  #twitter: ""
  instagram: "https://www.instagram.com/treepada/"
  #dribbble: ""
  linkedin: "www.linkedin.com/in/tarun-sreepada-4659a086"
  github: "https://www.github.com/Tarun-Sreepada"

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}]'
